"""Initial schema for the Personal Cognitive Digital Twin.

Creates every table plus, on PostgreSQL only, the pgvector IVFFlat index that
makes similar-decision retrieval scale past a sequential scan. On SQLite the
same retrieval runs as an in-process NumPy scan, so no index is needed.

Revision ID: 3bf97f16c149
Revises: 
Create Date: 2026-08-29 11:56:44.747984
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.database.types  # portable GUID / JSONB / pgvector column types


revision: str = '3bf97f16c149'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', app.database.types.GUID(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource', sa.String(length=120), nullable=False),
    sa.Column('detail', app.database.types.JSONDict(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('behavioral_traits',
    sa.Column('trait_key', sa.String(length=48), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('supporting_decisions', app.database.types.JSONDict(), nullable=False),
    sa.Column('user_override', sa.Float(), nullable=True),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('user_id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'trait_key', name='uq_trait_per_user')
    )
    with op.batch_alter_table('behavioral_traits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_behavioral_traits_trait_key'), ['trait_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_behavioral_traits_user_id'), ['user_id'], unique=False)

    op.create_table('embeddings',
    sa.Column('owner_type', sa.String(length=24), nullable=False),
    sa.Column('owner_id', app.database.types.GUID(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('vector', app.database.types.EmbeddingVector(), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('backend', sa.String(length=48), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('user_id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_type', 'owner_id', 'kind', name='uq_embedding_owner')
    )
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_embeddings_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_embeddings_owner_type'), ['owner_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_embeddings_user_id'), ['user_id'], unique=False)

    op.create_table('feedback',
    sa.Column('prediction_id', app.database.types.GUID(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('target_key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('detail', app.database.types.JSONDict(), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('user_id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_prediction_id'), ['prediction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_user_id'), ['user_id'], unique=False)

    op.create_table('memory_items',
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('detail', app.database.types.JSONDict(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('user_id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_items_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_items_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_items_user_id'), ['user_id'], unique=False)

    op.create_table('model_artifacts',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=True),
    sa.Column('metrics', app.database.types.JSONDict(), nullable=False),
    sa.Column('feature_names', app.database.types.JSONDict(), nullable=False),
    sa.Column('importances', app.database.types.JSONDict(), nullable=False),
    sa.Column('n_train_rows', sa.Integer(), nullable=False),
    sa.Column('n_train_decisions', sa.Integer(), nullable=False),
    sa.Column('cv_accuracy', sa.Float(), nullable=False),
    sa.Column('cv_brier', sa.Float(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('user_id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_artifacts_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_artifacts_user_id'), ['user_id'], unique=False)

    op.create_table('questionnaire_responses',
    sa.Column('item_key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('raw_value', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('user_id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_key', name='uq_questionnaire_item')
    )
    with op.batch_alter_table('questionnaire_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questionnaire_responses_item_key'), ['item_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_questionnaire_responses_user_id'), ['user_id'], unique=False)

    op.create_table('scenarios',
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('context', app.database.types.JSONDict(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('factors', app.database.types.JSONDict(), nullable=False),
    sa.Column('factor_source', sa.String(length=24), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('factor_evidence', app.database.types.JSONDict(), nullable=False),
    sa.Column('emotions', app.database.types.JSONDict(), nullable=False),
    sa.Column('is_hypothetical', sa.Boolean(), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('user_id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenarios_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_scenarios_user_id'), ['user_id'], unique=False)

    op.create_table('trait_evidence',
    sa.Column('trait_key', sa.String(length=48), nullable=False),
    sa.Column('decision_id', app.database.types.GUID(), nullable=True),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('observation', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('detail', app.database.types.JSONDict(), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('user_id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trait_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trait_evidence_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trait_evidence_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_trait_evidence_trait_key'), ['trait_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_trait_evidence_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('model_params', app.database.types.JSONDict(), nullable=False),
    sa.Column('preferences', app.database.types.JSONDict(), nullable=False),
    sa.Column('data_retention_days', sa.Integer(), nullable=False),
    sa.Column('allow_llm_processing', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('decision_factors',
    sa.Column('scenario_id', app.database.types.GUID(), nullable=False),
    sa.Column('factor_key', sa.String(length=48), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('evidence', app.database.types.JSONDict(), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decision_factors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_factors_factor_key'), ['factor_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_factors_scenario_id'), ['scenario_id'], unique=False)

    op.create_table('decisions',
    sa.Column('scenario_id', app.database.types.GUID(), nullable=False),
    sa.Column('chosen_option', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('emotional_state', app.database.types.JSONDict(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('expected_reward', sa.Float(), nullable=False),
    sa.Column('perceived_risk', sa.Float(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('satisfaction', sa.Float(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('user_id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_scenario_id'), ['scenario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_user_id'), ['user_id'], unique=False)

    op.create_table('predictions',
    sa.Column('scenario_id', app.database.types.GUID(), nullable=False),
    sa.Column('predicted_option', sa.Text(), nullable=False),
    sa.Column('predicted_probability', sa.Float(), nullable=False),
    sa.Column('confidence_label', sa.String(length=16), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('factors', app.database.types.JSONDict(), nullable=False),
    sa.Column('traits_snapshot', app.database.types.JSONDict(), nullable=False),
    sa.Column('layer_outputs', app.database.types.JSONDict(), nullable=False),
    sa.Column('explanation', app.database.types.JSONDict(), nullable=False),
    sa.Column('similar_decisions', app.database.types.JSONDict(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('is_counterfactual', sa.Boolean(), nullable=False),
    sa.Column('parent_prediction_id', app.database.types.GUID(), nullable=True),
    sa.Column('overrides', app.database.types.JSONDict(), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('user_id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_parent_prediction_id'), ['parent_prediction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_scenario_id'), ['scenario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_user_id'), ['user_id'], unique=False)

    op.create_table('decision_options',
    sa.Column('decision_id', app.database.types.GUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('was_chosen', sa.Boolean(), nullable=False),
    sa.Column('stance', app.database.types.JSONDict(), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decision_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_options_decision_id'), ['decision_id'], unique=False)

    op.create_table('prediction_options',
    sa.Column('prediction_id', app.database.types.GUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('utility', sa.Float(), nullable=False),
    sa.Column('stance', app.database.types.JSONDict(), nullable=False),
    sa.Column('contributions', app.database.types.JSONDict(), nullable=False),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prediction_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_options_prediction_id'), ['prediction_id'], unique=False)

    op.create_table('prediction_outcomes',
    sa.Column('prediction_id', app.database.types.GUID(), nullable=False),
    sa.Column('actual_option', sa.Text(), nullable=False),
    sa.Column('was_correct', sa.Boolean(), nullable=False),
    sa.Column('probability_of_actual', sa.Float(), nullable=False),
    sa.Column('brier_score', sa.Float(), nullable=False),
    sa.Column('log_loss', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('promoted_decision_id', app.database.types.GUID(), nullable=True),
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('user_id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prediction_outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_outcomes_prediction_id'), ['prediction_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_prediction_outcomes_promoted_decision_id'), ['promoted_decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_outcomes_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prediction_outcomes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


    create_vector_index()


def downgrade() -> None:
    drop_vector_index()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction_outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_outcomes_user_id'))
        batch_op.drop_index(batch_op.f('ix_prediction_outcomes_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_prediction_outcomes_promoted_decision_id'))
        batch_op.drop_index(batch_op.f('ix_prediction_outcomes_prediction_id'))

    op.drop_table('prediction_outcomes')
    with op.batch_alter_table('prediction_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_options_prediction_id'))

    op.drop_table('prediction_options')
    with op.batch_alter_table('decision_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_options_decision_id'))

    op.drop_table('decision_options')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_user_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_parent_prediction_id'))

    op.drop_table('predictions')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_user_id'))
        batch_op.drop_index(batch_op.f('ix_decisions_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_decisions_occurred_at'))

    op.drop_table('decisions')
    with op.batch_alter_table('decision_factors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_factors_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_decision_factors_factor_key'))

    op.drop_table('decision_factors')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('trait_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trait_evidence_user_id'))
        batch_op.drop_index(batch_op.f('ix_trait_evidence_trait_key'))
        batch_op.drop_index(batch_op.f('ix_trait_evidence_source'))
        batch_op.drop_index(batch_op.f('ix_trait_evidence_decision_id'))

    op.drop_table('trait_evidence')
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenarios_user_id'))
        batch_op.drop_index(batch_op.f('ix_scenarios_category'))

    op.drop_table('scenarios')
    with op.batch_alter_table('questionnaire_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questionnaire_responses_user_id'))
        batch_op.drop_index(batch_op.f('ix_questionnaire_responses_item_key'))

    op.drop_table('questionnaire_responses')
    with op.batch_alter_table('model_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_artifacts_user_id'))
        batch_op.drop_index(batch_op.f('ix_model_artifacts_kind'))

    op.drop_table('model_artifacts')
    with op.batch_alter_table('memory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_memory_items_kind'))
        batch_op.drop_index(batch_op.f('ix_memory_items_key'))

    op.drop_table('memory_items')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_prediction_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_kind'))

    op.drop_table('feedback')
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_embeddings_user_id'))
        batch_op.drop_index(batch_op.f('ix_embeddings_owner_type'))
        batch_op.drop_index(batch_op.f('ix_embeddings_owner_id'))

    op.drop_table('embeddings')
    with op.batch_alter_table('behavioral_traits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_behavioral_traits_user_id'))
        batch_op.drop_index(batch_op.f('ix_behavioral_traits_trait_key'))

    op.drop_table('behavioral_traits')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def create_vector_index() -> None:
    """IVFFlat index for cosine distance, PostgreSQL only.

    ``lists = 100`` suits the low-thousands of rows a single person's history
    produces. Postgres will not use an IVFFlat index until it has been built on
    populated data, so this is created empty and should be reindexed once real
    volume exists.
    """
    if not _is_postgres():
        return
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_embeddings_vector_cosine "
        "ON embeddings USING ivfflat (vector vector_cosine_ops) WITH (lists = 100)"
    )


def drop_vector_index() -> None:
    if _is_postgres():
        op.execute("DROP INDEX IF EXISTS ix_embeddings_vector_cosine")
